import { createAsyncThunk, createSlice } from "@reduxjs/toolkit"
import { RootState } from "../../app/store"
import {
  fetchPostsByAuthor,
  FetchPostsByAuthorParams,
} from "./postsByAuthorAPI"
import { PostContents} from "../posts/types";

export interface State {
  postsByAuthor: [] | PostContents[]
  status: "idle" | "loading" | "failed" | "success"
}

const initialState: State = {
  postsByAuthor: [],
  status: "idle",
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const fetchPostsByAuthorAsync = createAsyncThunk(
  "posts/fetchPostsByAuthor",
  async ({ authorId }: FetchPostsByAuthorParams) => {
    const response = await fetchPostsByAuthor({ authorId })
    // The value we return becomes the `fulfilled` action payload
    return response.data
  },
)

export const postsByAuthorSlice = createSlice({
  name: "postsByAuthor",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchPostsByAuthorAsync.pending, (state) => {
        state.status = "loading"
      })
      .addCase(fetchPostsByAuthorAsync.fulfilled, (state, action) => {
        state.status = "success"
        state.postsByAuthor = [...state.postsByAuthor, ...action.payload]
      })
      .addCase(fetchPostsByAuthorAsync.rejected, (state) => {
        state.status = "failed"
      })
  },
})

export const postsByAuthorStateSelector = (state: RootState) => state.postsByAuthor

export default postsByAuthorSlice.reducer
